### ISSUE TITLE
Hissing noise when playing DSF files

### ISSUE THREAD

**Issue by RobinpCP** [GioF71/squeezelite-docker#52] opened 2022-08-05 08:26 UTC
I'm using Libreelec on RPi 3B+.  My Docker-compose file is

version: "3.3"

services:
  squeezelite-tailscale:
    image: giof71/squeezelite:latest
    container_name: squeezelite-tailscale
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    environment:
      - SQUEEZELITE_NAME=Squeezelite-Docker
      - SQUEEZELITE_AUDIO_DEVICE=hw:CARD=sndrpihifiberry,DEV=0
      - SQUEEZELITE_TIMEOUT=3
      - STARTUP_DELAY_SEC=3
    restart: unless-stopped

These settings can play Flac and wav files.  My Hifiberry DAC2 Pro can support up to 192Khz/24bit which can play DSD64 files with no issues, because I've tried the following.

I downloaded Squeezelite from SourceForge and ran it from SSH terminal using command line 
/storage/squeezelite -o default:CARD=sndrpihifiberry -n 'Kodi-Squeezelite' -C 3

BTW, the latest version is now 1.9.9.1043.

**Comment by GioF71** [comment] 2022-08-05 13:18
Hello,
as far as I know, the HiFiBrerry DAC2 Pro does not natively play DSD. When it does appear to do so, it is because the player converts those files to regular PCM.

About the versions: 1403 is only for the ffmpeg version, which I am not using.  It seems I am still using the most recent version of SqueezeLite on my images, which in the case of armhf is currently 1401.
But this might be the answer: when you run squeezelite from the command line using that binary, your version of squeezelite is probably doing the conversion by itself. This will generate high(er) cpu usage on the player, something to be considered if your player is a raspberry pi 3 or 2.

You might try with the no-dsd preset which will tell the LMS server that the player cannot or does not want to play dsd natively. This should force the LMS server to do the conversion if needed.
Here is the updated docker-compose file:

```
---
version: "3.3"

services:
  squeezelite-tailscale:
  image: giof71/squeezelite:latest
  container_name: squeezelite-tailscale
  network_mode: host
  devices:
    - /dev/snd:/dev/snd
  environment:
    - PRESET=no-dsd
    - SQUEEZELITE_NAME=Squeezelite-Docker
    - SQUEEZELITE_AUDIO_DEVICE=hw:CARD=sndrpihifiberry,DEV=0
    - SQUEEZELITE_TIMEOUT=3
    - STARTUP_DELAY_SEC=3
  restart: unless-stopped
```

A side note: the suffix "-tailscale" for the service and container names is probably meaningless in your scenario. I am using those names for a RPI that I sometimes brought away from home and connected via a hotspot to my LMS server using the tailscale private network.

**Comment by RobinpCP** [comment] 2022-08-05 14:14
Thanks a lot for your quick response.  I'm pretty sure the DAC supports DoP because from player settings it states "This player supports native playback of DSD files. DSD-over-PCM should be configured on the player configuration interface."

Is there any way other than turning off DoP?

**Comment by GioF71** [comment] 2022-08-05 14:21
Hello, where did you see that quoted statement? Can you post a screenshot or a link?
I believe that this happens because you are using the ffmpeg binary, but I might be wrong.
If I look at the specifications of your board [here](https://www.hifiberry.com/shop/boards/hifiberry-dac2-pro/) and its [datasheet](https://www.hifiberry.com/docs/data-sheets/datasheet-dac2-pro/) there is no mention for dsd.

**Comment by GioF71** [comment] 2022-08-05 14:26
In any case, you can enable DOP with the property 
SQUEEZELITE_DELAY=500,dop
Let me know if this helps.

**Comment by GioF71** [comment] 2022-08-05 14:33
Also, you can make sure of how the player is playing your files using this command line:

cat /proc/asound/*/pcm*p/sub*/hw_params

Sorry for the asterisks but I do not exactly know the name of the hifiberry card.
If the card is playing DSD, it should be understandable from the output of that command. Otherwise it will show some pcm sampling rate like 88200,176400,192000 or similar.

**Comment by RobinpCP** [comment] 2022-08-05 14:37
I made a screenshot but could not find a way to paste it.  The statement is in Player settings -> Extra settings -> DSDPlayer 

I've tried SQUEEZELITE_DELAY=500,dop with no luck.

**Comment by GioF71** [comment] 2022-08-05 14:38
try without the ",dop", it was my mistake. I corrected the post.

**Comment by RobinpCP** [comment] 2022-08-05 14:40
LibreELEC:~ # cat /proc/asound/card0/pcm0p/sub0/hw_params
access: MMAP_INTERLEAVED
format: S32_LE
subformat: STD
channels: 2
rate: 176400 (352800/2)
period_size: 1764
buffer_size: 7056

**Comment by GioF71** [comment] 2022-08-05 14:41
Yes, that's unfortunately not DSD, it is converted to PCM at 176.4kHz

**Comment by GioF71** [comment] 2022-08-05 14:44
There are boards which support dsd natively. See [here](https://www.audiophonics.fr/en/search?search_query=dsd+raspberry+pi) for example.

**Comment by RobinpCP** [comment] 2022-08-05 14:44
I've tried 500 and 500,dop.  Both did not work.

So, can my DAC support DoP?

**Comment by GioF71** [comment] 2022-08-05 14:46
If [this](https://www.hifiberry.com/shop/boards/hifiberry-dac2-pro/) is your board, I am afraid it cannot, sorry!

**Comment by RobinpCP** [comment] 2022-08-05 14:51
I see.  Thanks a lot for your help.  Just wonder why the statement...

**Comment by GioF71** [comment] 2022-08-05 14:54
Well, you can try with the binary without the "-ffmpeg" ([this one](https://sourceforge.net/projects/lmsclients/files/squeezelite/linux/squeezelite-1.9.9.1401-armhf.tar.gz/download).
It will probably behave like the docker container.
The -ffmpeg version probably presents itself as dsd-capable because it can convert dsd to pcm without any help from the server.

**Comment by RobinpCP** [comment] 2022-08-06 00:44
I had used command line squeezelite for over one year with a few versions before switching to your docker version.  I did not experience any hissing noise.

I have played with your docker version and found something odd.

If I add "- SQUEEZELITE_RATES=96000", it can play DSD64 but the player shows
access: MMAP_INTERLEAVED
format: S32_LE
subformat: STD
channels: 2
rate: 352800 (352800/1)
period_size: 3528
buffer_size: 14112

If I add "- SQUEEZELITE_UPSAMPLING=v::4:28:95:105:45" in addition, it can play DSD64, but then the player shows
access: MMAP_INTERLEAVED
format: S32_LE
subformat: STD
channels: 2
rate: 88200 (352800/4)
period_size: 882
buffer_size: 3528

However if I change the rate to 192000 or 352800 with or without upsampling, it can NOT play DSD64 and the player shows
access: MMAP_INTERLEAVED
format: S32_LE
subformat: STD
channels: 2
rate: 176400 (352800/2)
period_size: 1764
buffer_size: 7056

In all cases, I think the player DoP is enabled or at least the statement is shown.

**Comment by GioF71** [comment] 2022-08-18 22:17
Hello, sorry for the late answer, but I currently don't have access to any device I could use in order to perform some tests.
But I might be able to try and reproduce your issue in a few days from now.
Do you mind providing a sample file? I believe one of my boards is the same as yours or very similar.
Alternatively, do you have a specific request for a change on this container image?

Cheers

**Comment by RobinpCP** [comment] 2022-08-20 02:44
Sorry, I no longer use it.  Thanks.

**Comment by GioF71** [comment] 2022-08-20 12:23
Ok, I am closing the issue then.
Cheers.

**Closed** 2022-08-20 12:23 UTC
